version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_OMDB_API_KEY=${REACT_APP_OMDB_API_KEY}
    restart: unless-stopped 